### ISSUE TITLE
APTTokenizer integration

### ISSUE THREAD

**Issue by Muedi** [OpenBioML/protein-lm-scaling#12]
Hi @jamaliki , I was trying to use the tokenizer instead of the autotokenizer pretrained one. However, when I instantiate it, it is not callable opposed to the autotokenizer from the pretrained checkpoint. 
I guess, I need to write a wrapper? Any pointers?

One Other thing, the AptTokenizer needs the list of tokens to be initialized, but assignes a list of tokens to self.ids_to_tokens itself, so the provided tokens are not used anyways right?

 Thanks for any input :)

**Comment by jamaliki** [comment]
Hi @Muedi , good catch on the AptTokenizer, I'll fix it right now. 

For your first question, did `tokenizer.encode(string)` not work? Are you looking for something like `tokenizer(string)`? I can add that too

**Comment by Muedi** [comment]
I saw the encode and batch_encode functions just after posting lol.

However, while trying this: 


def tokenize(batch):
    return tokenizer.batch_encode(batch["mutated_sequence"])

I got a quite obscure (at least for me) error message: 
TypeError: Provided `function` which is applied to all elements of table returns a variable of type . Make sure provided `function` returns a variable of type `dict` (or a pyarrow table) to update the dataset or `None` if you are only interested in side effects.

>  Are you looking for something like tokenizer(string)?
We can add the __call__ later, I think its nice to have but not necessary! :) 

A feature that we should think about to have though would be different kinds of padding or truncation, I think? Or will our model handle different length easily anyway?

**Comment by jamaliki** [comment]
Hmm, it seems to work on my end
```
>>> from protein_lm.tokenizer import AptTokenizer
>>> seqs = ["ARRRRRYYYYT", "GGGGGGHHHHHAAAA"]
>>> tokenizer = AptTokenizer()
>>> tokenizer.encode_batch(seqs)
[[4, 9, 9, 9, 9, 9, 18, 18, 18, 18, 10], [5, 5, 5, 5, 5, 5, 20, 20, 20, 20, 20, 4, 4, 4, 4]]
```

Did you reinstall the `rust_trie`? I had made a change. Could you try installing it again?

**Comment by Muedi** [comment]
I guess it is related to the input format? 
It will be tensors or dicts I think, perhaps as is it can only handle lists? 
I'll play around a bit tomorrow!


The installation is fresh so it should work out :)

**Comment by jamaliki** [comment]
So the output supports tensors, you just set `return_tensor=True`. If you mean the input, I think any iterable should be fine. If I could just get your use case I can add the functionality :)

**Comment by Muedi** [comment]
My usecase is the current Protein gym.py script in this repo.

I wanted to switch the AutoTokenizer with your new one (I expected it to inherit from the HF tokenizers for some reason:D)

**Comment by Muedi** [comment]
Ok I tested around a bit. The installation works and so did your example from above.
It is also not a problem of the input format, as this is actually just a list of strings. :)

The problem was in the function used for mapping the tokenizer!

So I needed to go from:

"""tokenizer = AptTokenizer(tokens)

def tokenize(batch):
    return tokenizer(batch["mutated_sequence"])

token_data = dataset.map(tokenize, batched=True)"""

to 

"""tokenizer = AptTokenizer(tokens)

def tokenize(batch):
    tokens = tokenizer(batch["mutated_sequence"])
    return {"input_ids": tokens}

token_data = dataset.map(tokenize, batched=True)"""

You were right, it is much faster than the ESM2 one. 

However, the trainer stuff of Huggingface does work with when the tokenizer is not passed, but it is needed only for padding, which we did already when using the batched_encode function. 

I wrote a simple  \__call\__() function, I'll push it and ask for your review :)

**Comment by Muedi** [comment]
reopened for the callability :)

**Comment by jamaliki** [comment]
Awesome work!

**Comment by jamaliki** [comment]
I think we can close this now, @Muedi ?

**Comment by talkhanz** [comment]
does the tokenizer call now support the attributes trunction,padding and max_length like [here](https://github.com/OpenBioML/protein-lm-scaling/blob/788b44681315c8ada8a2235a9f5519ec6b79c032/Protein-gym.py#L79)

**Comment by Muedi** [comment]
Hi, 

as is the tokenizer doesn't support this, the trainer worked without these features, too, as it is just used for padding in that context. 

I saw that you also utilize the trainer class and function though, so we perhaps should think of implementing it to be useable with this, @jamaliki ?

However, as is the padding is done regardless and the trainer loop works.

**Comment by talkhanz** [comment]
yeah i just realized the batch_encode code could do the padding if we set return_tensors=True

**Comment by jamaliki** [comment]
Yeah, I'm going to look into making it 100% API compatible with the Huggingface tokenizer
