### ISSUE TITLE
Add contact predictions to evaluation framework

### ISSUE THREAD

**Issue by pascalnotin** [OpenBioML/protein-lm-scaling#19]

**Comment by csjackson0** [comment]
1. Create new "contact_prediction.ipynb" that modifies [BERT_esm1b.ipynb](https://github.com/sokrypton/algosb_2021/blob/main/BERT_esm1b.ipynb) to use APT model outputs for contact prediction. 
2. Create "utils.py" file and add functions from [https://github.com/sokrypton/algosb_2021/blob/main/utils.py](url) and [esm](https://github.com/facebookresearch/esm/blob/main/examples/contact_prediction.ipynb).
3. Add modified "contact_prediction.ipynb" and "utils.py" under evaluation/scripts dir.

**Comment by Muedi** [comment]
Hi I just wanted to add, that at the moment the eval script just uses esm-fair's pip install, so you could also rely on that and there would be no need for esm functions in a utils.py script, except you plan changes of course :)

**Comment by pascalnotin** [comment]
Closing this issue as it was addressed by [PR#54](https://github.com/OpenBioML/protein-lm-scaling/pull/54). Thanks again @csjackson0 !
