### ISSUE TITLE
Integrate rotary position encoding

### ISSUE THREAD

**Issue by pascalnotin** [OpenBioML/protein-lm-scaling#21]
1. Create a new dir under modeling called "utils" with an __init__.py and a "rotary_embedding.py" python file
2. Instantiate [rotary embedding](https://arxiv.org/abs/2104.09864) (see for example this file for possible instantiation: https://github.com/facebookresearch/esm/blob/main/esm/rotary_embedding.py)
3. Adapt [APT model class](https://github.com/OpenBioML/protein-lm-scaling/blob/main/protein_lm/modeling/models/apt/model_pytorch.py) to support rotary (user will pass in the type of position encoding to use via the [config file](https://github.com/OpenBioML/protein-lm-scaling/blob/main/protein_lm/modeling/models/apt/config.py#L18).

**Comment by csjackson0** [comment]
@pascalnotin I would like to work on this! Thank you for adding detailed requirements.

**Comment by NZ99** [comment]
Hey @csjackson0, any update on this? Do you think it would be possible to integrate [ReRope](https://github.com/bojone/rerope) at the same time? It would help w.r.t. sequence length generalization, which while not absolutely necessary would still be great to have.

Let me know if you need any help.

**Comment by pascalnotin** [comment]
Core features for this issue integrated as part of https://github.com/OpenBioML/protein-lm-scaling/pull/23.
@NZ99 - great idea re: ReRope. Just created a separate issue for it [here](https://github.com/OpenBioML/protein-lm-scaling/issues/34).
