### ISSUE TITLE
Instantiate AA tokenizer (HF)

### ISSUE THREAD

**Issue by pascalnotin** [OpenBioML/protein-lm-scaling#3]
Using HF tokenizer to facilitate compatibility with base model class

**Comment by jamaliki** [comment]
We could use the ESM tokenizer? Unless people have strong preferences.

```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("facebook/esm2_t33_650M_UR50D")
```

**Comment by pascalnotin** [comment]
Ok but we need to be careful with preprocessing since they seem to have kept indeterminate AAs (X,B,Z) and rare AAs (eg selenocysteine U) as part of the vocabulary (https://huggingface.co/facebook/esm2_t33_650M_UR50D/resolve/main/vocab.txt)

**Comment by jamaliki** [comment]
Yes, we should discuss this. It is quite easy to change as well.

**Comment by pascalnotin** [comment]
Closing this issue post merge. Thank you @jamaliki !
