### ISSUE TITLE
Integrate ReRope position encoding

### ISSUE THREAD

**Issue by pascalnotin** [OpenBioML/protein-lm-scaling#34]
Integrate ReRope position encoding and friends.

Reference implementations: 
- ReRope: https://github.com/bojone/rerope
- Other rotary variants: https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py

Implementation should be consistent with that of other position encoding schemes (eg., rotary, alibi). 

Issue resolution should also include unit tests to validate position encodings are as expected.

**Comment by talkhanz** [comment]
hey @pascalnotin. I was wondering if we should add unit tests for these encoding schemes to check if our encoding is working as intended (maybe take a random vector and see how operations on that result in an as expected output?). We'll probably add more schemes in the future so it would be nice if we contributors verify their contributions through some sort of unit tests?

**Comment by talkhanz** [comment]
it seems @NZ99 requested  @csjackson0! in another thread so its only fair I'll leave it up to him. There are many other variants of rope possible from [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py)
that I can follow up if needed.

**Comment by pascalnotin** [comment]
@talkhanz - sounds good re: your suggestions for unit tests and including the other rope variants as per the llama codebase as you suggested. Will edit the issue description. Thanks!

**Comment by talkhanz** [comment]
> @talkhanz - sounds good re: your suggestions for unit tests and including the other rope variants as per the llama codebase as you suggested. Will edit the issue description. Thanks!
Thanks for accommodating my feedback. Time to get to work!

**Comment by csjackson0** [comment]
@talkhanz thanks for checking in! I am working on FIM, but I am also happy to help with this issue.

**Comment by talkhanz** [comment]
@csjackson0 is working on the variants I suggested from the Llama and im working on rerope. Currently, the strategy we are thinking to test the encoding is to follow some ideas from the tests at hugging face [here](https://github.com/huggingface/transformers/blob/0afa5071bd84e44301750fdc594e33db102cf374/tests/models/gpt2/test_modeling_gpt2.py#L254)

To avoid merge conflicts, we are thinking of working in separate files for now, one for each variant. 
We can streamline things in 1 file once all variants are integrated?  
How does that @pascalnotin ?

**Comment by pascalnotin** [comment]
Sounds good - thank you both!

**Comment by talkhanz** [comment]
@csjackson0  FYI i've made a PR incorporating rerope. hopefully it help us avoid PR conflicts for your other LLama rotary variants!
