### ISSUE TITLE
Epochs not changing

### ISSUE THREAD

**Issue by talkhanz** [OpenBioML/protein-lm-scaling#36]
num_train_epochs in protein_lm/configs/train/toy_localcsv.yaml doesnt seem to be changing the number of training epochs.

Note the epoch value is being passed in the dictionary thats printed on the terminal when we run python train.py but I dont see the training loop actually running for that number of epochs

**Comment by othertea** [comment]
Sorry about that! After #37 is merged, you should be able to set `max_steps` to -1, and then `num_train_epochs` should actually change the number of training epochs.

**Comment by talkhanz** [comment]
No need to apologize! Thankyou for the quick PR!

**Comment by othertea** [comment]
@talkhanz #37 has been merged! Let me know if `num_train_epochs` works for you now, after setting `max_steps` to `-1`.

**Comment by talkhanz** [comment]
looks good. thank you!
