### ISSUE TITLE
Make an alternate gpu environment specification

### ISSUE THREAD

**Issue by othertea** [OpenBioML/protein-lm-scaling#53]
Our current yaml for creating environments is for cpu only and does not specify downloading the cuda version of pytorch. This issue is to create an alternate specification of dependencies for computers with gpus. You can do this by

* creating another yaml that specifies alternate dependencies
* modifying `setup.py`
* creating an appropriate `pyproject.toml`

Of course, we are open to other ways of doing this, if you prefer!

**Comment by Muedi** [comment]
Would setup.py actually need to modified? It contains basically only the call to get_packages right?

**Comment by othertea** [comment]
Sorry, to clarify, I meant you could do one of those options, not that you had to do all three!

**Comment by Muedi** [comment]
I went the yaml way and added an extra one for the cuda install and added the info to the readme. I'll send a PR when my other one is through :)
