### ISSUE TITLE
Project view

### ISSUE THREAD

**Issue by Muedi** [OpenBioML/protein-lm-scaling#8]
Hi is the project page meant to be reworked by everybody? 
I seem to not be able to assign myself, or move things from todo to in progress.

best, 
Max

**Comment by pascalnotin** [comment]
@Muedi - closing this issue as the self-assignment seems to now be handled properly with the `\take' command as implemented by @NZ99. Ill keep an eye on moving things from todo to in progress if that's not something you can do still.
